# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: publish

on:
  release:
    types:
      - created

jobs:
  sdist:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup python3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install requires
        run: python -m pip install twine wheel

      - name: Build source package
        run: python setup.py sdist

      - name: Publishing to pypi
        run: twine upload dist/*.tar.gz
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}

  wheel:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        include:
          # Ubuntu
          - python: '3.6'
            os: ubuntu-latest
          - python: '3.7'
            os: ubuntu-latest
          - python: '3.8'
            os: ubuntu-latest
          - python: '3.9'
            os: ubuntu-latest
          # MacOS
          - python: '3.6'
            os: macos-latest
          - python: '3.7'
            os: macos-latest
          - python: '3.8'
            os: macos-latest
          - python: '3.9'
            os: macos-latest
          # Windows
          - python: '3.6'
            os: windows-latest
          - python: '3.7'
            os: windows-latest
          - python: '3.8'
            os: windows-latest
          - python: '3.9'
            os: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup python${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python }}"

      - name: Install requires
        run: python -m pip install twine wheel

      - name: Build wheel for python "${{ matrix.python }}"
        run: python setup.py bdist_wheel

      - name: Publishing to pypi
        run: twine upload dist/*.whl
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
